apiVersion: v1
kind: PersistentVolume
metadata:
  labels: 
    type: local
  name: pv-hostpath
spec:
  storageClassName: manual
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/hostpathdir"  
