# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  # Minikube node
  config.vm.define "minikube" do |mkube|
    mkube.vm.box = "centos/7"
    mkube.vm.hostname = "mkube.example.com"
    mkube.vm.network "private_network", ip: "172.42.42.200"
    mkube.vm.provider "virtualbox" do |v|
      v.gui= true
	  v.name = "mkube"
      v.memory = 2048
      v.cpus = 1
    end
  end
end

